### ISSUE TITLE
CoreMod Dependencies

### ISSUE THREAD

**Issue by Ivorforce** [MinecraftForge/FML#551]
FML provides no good way for coremods to display dependency problems. Currently I am just throwing a custom exception and error message if my dependency is not there. If I don't throw the exception, FML will just call 'getASMTransformerClass' and receive a CNFE for trying to load a class that has an unknown superclass.

The dependency is used to make the class transformation process a lot simpler - e.g. register specific hooks and log errors if they are not handled. Basically just a personal coremod framework in the most general sense.

I'm gonna throw this out there and leave it up for discussion if coremods should be able to handle dependencies. If not, I'll probably remove the asm stuff from my framework and just move it all into the coremod instead.

**Comment by LunNova** [comment]
@Ivorforce 
I don't see a PR for this, did you abandon it/don't care any more?

Still not implemented in current Forge, so I'll make a PR for it over there unless you still want to do it.

Is `@DependsOn` just supposed to check if it's present, and not do anything regarding ordering, leaving all ordering behavior as it is just now with `@SortingIndex`?

**Comment by cpw** [comment]
It wouldn't be accepted sorry. Sorting index isn't great, but it is sufficient, and is compatible with non core mod tweakers..

**Comment by LunNova** [comment]
Okay. Could you add `@Deprecated`/something to `IFMLLoadingPlugin.DependsOn` indicating that it doesn't do anything?

**Comment by cpw** [comment]
Heh I should remove it. It never worked..

**Comment by LunNova** [comment]
Does this make sense as a way of implementing it without breaking SortIndex stuff?

`@DependsOn` can either be a full class name or the short name (the one defined with `@Name`, or short class name if not specified).

If you have a `@SortIndex` annotation, `@DependsOn` does not change it.
Else, `@DependsOn` sets your SortIndex to `(class you depend on's SortIndex) + 1`.
If you have multiple `@DependsOn`, it is set to `(highest SortIndex of any of your dependencies) + 1`.

If your `@DependsOn` refers to a class/short name which can't be found, throw a dependency error.
Cyclic dependencies will not be handled or detected, keep it simple and just loop through the list of tweakers once and set the sortindex prior to sorting.

It'd be nice to be able to `@DependsOn("FMLDeobfTweaker")` instead of the magic 1001 sortindex, and it seems a bit of a waste to just get rid of DependsOn :(

edit: Fixed formatting, I responded by email instead of online and line wrapping happened

**Comment by Ivorforce** [comment]
Honestly, I'd mostly like this annotation for real CoreMod library dependencies. Currently I just throw a hacky error in the log, but a proper error screen like FML does would be handy.

**Comment by LexManos** [comment]
Thats the thing, coremods CANT do that as they are loaded before screens.
People who make coremods need to not be stupid. There should only be like 4 of them in your entire mod  instance because 99% of the things you want to do with coremods you don't need to do with coremods.
Coremods are NOT Libraries and should NOT be used inter-twined.
