### ISSUE TITLE
Kotlin ILanguageAdapter and libraries

### ISSUE THREAD

**Issue by Emberwalker** [MinecraftForge/FML#633]
Kotlin works for the most part using the straight Java adapter (including @EventHandler), however it suffers when the @Mod annotated bit is an Object (but a Class does work). It probably needs some changes a la the Scala adapter. There's probably more obscure features I haven't tested yet that may be busted.

The Kotlin stdlib/reflect jars would also need to be added to the standard distribution, but these are far smaller than scala-library and friends. JetBrains also produce an official Gradle plugin, which can be loaded with "apply 'kotlin'" just like with Scala.

All these should be relatively easy to fix with a new ILanguageAdapter. If nobody adopts this, I'll look at it myself when I get a chance.

**Comment by LexManos** [comment]
No there is no intention to add any other language system to the loading mechanics natively in Forge. If I could I would remove Scala as it is nothing but a headake. But to many people would complain.
Feel free to write a mod that adds this loading mechanics, the system is fairly easy to plugin to because of the way it was designed. But natively no, there is no reason for this, and the logistics would be a nightmare.
