### ISSUE TITLE
Latest Forge Optifine Incompatibility [10.13.4.1472]

### ISSUE THREAD

**Issue by michaelproeber** [MinecraftForge/FML#664]
http://www.minecraftforum.net/forums/support/modded-client-support/2455083-modpack-crash-when-adding-optifine 

This thread brought the issue up which I had been experiencing because I updated my modpack to the latest Forge. Now I know you should use the recommended version of Forge anyway but some mod devs use the latest version and I wanted to bring it to your guys' attention. Crash logs and descriptions are all on that thread. Thanks c: The recommended version he used, I believe, was .1448.

**Comment by michaelproeber** [comment]
It's also very notable that shaders causes a crash report listed here with version 1472. I fixed it by downgrading as well. double-whammy! It was an crash about texture stitching which is something that 1472 (or at least a version after 1448) introduced along with the loading screen displaying texture stitching. Texture map, which was the Optifine error, was probably involved with stitching or a related loading process.
http://paste.ubuntu.com/11759329/

**Comment by LexManos** [comment]
Do not make new issues in the FML repo this is archive only.
And yes, sometimes Optifine breaks, due to how it touches everything so deeply inside of Minecraft we can't really do anything about that you will need to wait for them to update.
As for shaders I do not know, again, they hook in deeply to rendering and cause issues.
Speak with them about updating.
